theme: jekyll-theme-minimal
logo: /assets/img/r3-training-logo.png
title: Basic git training - Practice repository
description: This is a practice repository for basic git training.
url: https://lcsb-biocore.github.io/basic-git-practice/
collections:
  attendees:
    output: true
